### ISSUE TITLE
Metrics 

### ISSUE THREAD

**Issue by rensmere** [osuosl/streamwebs#1]
A way to easily pull and look at user information on site such as: # of users (students vs. teachers), # of project sites, # of datasheets uploaded, # of curriculum downloads, user emails, etc.

**Comment by Kennric** [comment]
We just need to associate a google account, then google analytics will be easy to include in the existing any new site.

**Comment by Kennric** [comment]
existing google account: streamwebsoregon@gmail.com

**Comment by tschuy** [comment]
This will need more than GA can offer -- GA is more for active site visitors while it sounds like @rensmere wants more broad stats about users and uploaded data.

However, it would be nice to add some [custom dimensions](https://developers.google.com/analytics/devguides/collection/analyticsjs/custom-dims-mets) regarding logged in/logged out users. This would allow you to view # of logged in teachers, students, etc
