### ISSUE TITLE
Error message when graphing

### ISSUE THREAD

**Issue by rensmere** [osuosl/streamwebs#10]
Data graphing error that reads “data column for axis #0 cannot be of type string for the following site.

I am specifically interested in the site Wiley Creek on the collection date 9/21/15 http://streamwebs.org/water-quality-data-graphing?site=4976 

I have to visit a class next week to follow up with them on this data and would love to have it work.  I tried just doing individual parameters (DO, pH, temp, etc) and unchecked all of them with still no luck.

**Comment by Kennric** [comment]
I'm working on this - the problem seems to be for that specific date, some of the fields are empty, I am trying to untangle where it is throwing the error, will update here as soon as I can make some progress.

**Comment by Kennric** [comment]
OK, I finally located the issue, which is not empty fields, but the selection of a single date, which translated into a query over a time frame of zero length (between today at 12:00 and today at 12:00). I changed the code to select 00:00:00 o'clock to 23:59:59 o'clock, and the graphing appears to be correct now. Please test and let me know if anything looks amiss.

**Comment by rensmere** [comment]
Thanks Ken! It does appear to be working.  If you have a chance can you look at another issue that I am finding?  When I am looking at graphing macro invertebrate data for a single date (09/30/2015) no data is registering on the graph.  There isn’t much data for this date but there is some so it seems like it should show up on a graph? http://streamwebs.org/macroinvertebrates?site=4976

This is also data that I would like to look at with students when I go out to their school next week.

Thanks!

Renee



On Nov 24, 2015, at 5:01 PM, Kennric <notifications@github.com<mailto:notifications@github.com>> wrote:

.

**Comment by rensmere** [comment]
I think that is the same issue - I adjusted the times accordingly,
please test.

Also, I noticed that the form was submitting to the wrong view - the
graph view is
http://streamwebs.org/macroinvertebrates-data-graphing?site=4976, but
when you put in dates and click submit, it was going to
http://streamwebs.org/macroinvertebrates?site=4976, which seems to have
mostly the same code, but was not rendering the same way. I've changed
this, and things seems to work a little more predictably now.


Thanks,
Ken
