### ISSUE TITLE
Django Form for CC [8]

### ISSUE THREAD

**Issue by athai** [osuosl/streamwebs#104]
Write form logic for the Canopy Cover Survey datasheet.

Check out this [PR](https://github.com/osuosl/streamwebs/pull/93) for an example of how to implement. Note that you'll be working w/ submodules, so the logic may be a little different. Annie's [PR](https://github.com/osuosl/streamwebs/pull/88) may serve as a good reference.

Links to the django docs --
https://docs.djangoproject.com/en/1.9/topics/forms/
https://docs.djangoproject.com/en/1.9/ref/forms/api/

And the datasheet! --
http://streamwebs-dev.osuosl.org/sites/streamwebs/files/files/Canopy_OSU.pdf

**Comment by cthalmann** [comment]
Closed via #109
