### ISSUE TITLE
Datasheet: Water Quality Views and Templates [8]

### ISSUE THREAD

**Issue by leian7** [osuosl/streamwebs#112]
The views and templates for WQ already exist, but need to be synced with the new Django model forms that @elenatorrey has implemented. Tests also need to be implemented.

- Modify data sheet submission view and corresponding template to incorporate forms
- Modify submitted data sheet view view and corresponding template to display saved data
- Route URLs
- Write tests

**Comment by athai** [comment]
Resolved by #127
