### ISSUE TITLE
site_slug's are not guaranteed to be unique, and will break code if they aren't.

### ISSUE THREAD

**Issue by lo9key** [osuosl/streamwebs#124]
I noticed that in several places we're using code like `site = Site.objects.get(site_slug=site_slug)` which [will break](https://docs.djangoproject.com/en/1.10/ref/models/querysets/#get) if there is more than one result.  Right now the admin page allows me to add/edit sites using non-unique site_slugs.

Maybe the plan is to limit this problem by keeping the admin page away from the users, but I thought it was worth mentioning.

**Comment by athai** [comment]
Let's just nuke the site_slug and retrieve everything by ID. It'll be easier in the long run, especially since the pre-existing sites don't have slugs associated with them.

**Comment by athai** [comment]
Superseded by #133.
