### ISSUE TITLE
Resources page [1]

### ISSUE THREAD

**Issue by athai** [osuosl/streamwebs#131]
Set up a blank `Resources` page

**Comment by lo9key** [comment]
@athai Would you like me to include the text and files like the original [resources](http://streamwebs.org/resources) page?

**Comment by athai** [comment]
I think for now, just have plaintext placeholders. Since we're not entirely sure how much info we want to keep on the ``Resources`` page, it seems silly to invest too much time into this.

**Comment by athai** [comment]
Resolved by #212, #213, #217, and #218
