### ISSUE TITLE
Reporting Method - admin site stats [5]

### ISSUE THREAD

**Issue by athai** [osuosl/streamwebs#134]
Create a view that will allow Renee to query StreamWebs for site stats.

First off, make it so that she can query the number of active users. Functionality to get other stats (like active sites, number of datasheets per site, etc.) will be added to this view later.

**Comment by leian7** [comment]
To recap, the stats view will include:
- num active sites
- num active users
- num active schools (focus on this one last so we can figure out how to identify which schools are active from our migrated data)
- num data sheets (for each site + holistically)

Any "admin" user will have access to this view.

**Comment by leian7** [comment]
Closed via #223
