### ISSUE TITLE
Merge Order

### ISSUE THREAD

**Issue by athai** [osuosl/streamwebs#135]
UPDATED November 7, 2016
--

The following is a list of open PRs (and the order in which they should be merged).
1. ~~#162 - CSS for Macroinvertebrate data sheets~~
2. ~~#161 - CSS for login, registration, and index~~
3. ~~#66 - CSS for Existing views (sites, data sheets, etc.)~~
4. ~~#171 - Fix Macro Graphing~~
5. ~~#145 - WQ graphs (WIP)~~

Not yet affected by merge order:
- ~~#175 - Import all data with one script (WIP)~~
- ~~#131 - Resources pages (WIP)~~
- ~~#134 - Reporting method: Get active users~~
- ~~#89 - Background graphics~~
- ~~#174 - Soil Survey Form and Views (Basic)~~
- ~~#169 - Fix incorrect uses of slug/site names~~

**Comment by lo9key** [comment]
@athai it may be easier to merge #130 before #127, so the CSS files will be available while adjusting the water quality template.  Otherwise @subnomo will need to make a lot of adjustments to my template.

**Comment by subnomo** [comment]
#130 merges into `subnomo/styling` not `develop`, so we should still merge #127 first.

Forgot to tell you that @lo9key, my bad.

**Comment by lo9key** [comment]
Isn't it going to be a nightmare to keep `subnomo/styling` up to date with `develop`, while people are making frequent changes to both branches?  It seems like @subnomo will eventually face an epic merge conflict.

**Comment by subnomo** [comment]
@lo9key Yep. I've already run into many conflicts that I had to rebase. :cry:

`subnomo/styling` contains breaking changes, however, so merging it before all the views are updated would break the site.

**Comment by alxngyn** [comment]
add 
#6.5 UserProfiles modification + Users migration

**Comment by leian7** [comment]
#60 photo point
