### ISSUE TITLE
Site CRUD: Add google maps

### ISSUE THREAD

**Issue by leian7** [osuosl/streamwebs#148]
Create, Read, and Update need to have Google Maps functionality, i.e. when the user creates/updates a site they can click a point on the Google map and that point will be stored as the site's `location` value.

In addition, the `sites` view (streamwebs/sites/) needs to be updated to not include site type + other refinements.

**Comment by leian7** [comment]
Bug: On the ``sites`` view, no matter which site marker you click on, it only gives you the description/name of the last site. For example, here no matter which marker you click on, it brings up Zigzag, the last site in the database:
![sites_map_bug](https://cloud.githubusercontent.com/assets/9158473/18481645/c2030cae-7991-11e6-9add-8999894567ea.png)

**Comment by subnomo** [comment]
@leian7 I have fixed this bug on the CSS branch. See https://github.com/osuosl/streamwebs/pull/66/commits/1f8869969093e21411f69b9d65ac41dabe705bde.

**Comment by athai** [comment]
Fixed by #66.
