### ISSUE TITLE
Bugs on the sites page

### ISSUE THREAD

**Issue by athai** [osuosl/streamwebs#158]
- The map is zoomed in too far (centering on a corner of Nevada), making it look like there are no sites being displayed
- The dropdown menu doesn't list any site names
- Pop-up/labels (for each of the site markers) don't seem to work?

**Comment by leian7** [comment]
Additionally, we need to remove the student stewardship, salmon watch, etc. checkboxes since we are no longer categorizing sites like this.

**Comment by LyonesGamer** [comment]
All except the zooming issue are fixed in #169 and #172. I'll fix the zooming, but the centering is weird: it should be centering at 44N 122W, which is in roughly the center of Oregon. No clue why it's centering on Nevada...

**Comment by athai** [comment]
Resolved by #169, #172, and #185
