### ISSUE TITLE
How to handle Canopy Cover data

### ISSUE THREAD

**Issue by LyonesGamer** [osuosl/streamwebs#165]
The canopy cover data sheet is...a bit strange, to say the least. It's a 6x6 grid, with the central 24 (approximating a circle) actually storing data. This data is purely boolean.

The question is, how do we store and display this data?

One way would be to store a boolean for each square. Label them from A-X, and simply store `A=true, B=false, C=false, ...` I'd like to avoid having 24 extra columns in the database, plus passing around a huge object with 24 fields or doing a fair bit of processing to get a 24-element array. That said, it is the most clear and readable, so it has pros and cons.

An alternate route would be to handle it via bit arithmetic. We store and send the data back and forth as a number, and bitshift out the boolean data on the front-end. That is, on the right-most 24 bits of an integer, we store each square's data as a bit, then we pass that number back and forth. On the frontend, we can quickly bitshift out the data and display it very efficiently, and as far as the backend is concerned, it's just a number. The downside is, this may not be as clear or maintainable for future devs, and it presents a bit of a hassle for importing the data from the Drupal site.

I'd like to start a discussion on which one people would like more.

I wrote up a quick example of an implementation using the Bit-Shift method here: http://files.lyonesgamer.com/streamwebs-bitshift-canopy-cover.html

**Comment by Kennric** [comment]
This method is in practice not that different from storing a comma delimited string, one char per box, and splitting it out in code to address as an array. Bits are much more operation and space efficient, but I think maintainability is a bigger concern. If everyone is comfortable with both javascript and python for creating and manipulating an integer bit-wise, I think this is fine, but if confusion about it is going to cost us more than we gain over the cruder method, then crude wins. 

I definitely don't think a db row per box is necessary. Let's put the data in a string or integer in one field.

**Comment by Kennric** [comment]
For reference: https://wiki.python.org/moin/BitManipulation

**Comment by athai** [comment]
Honestly, I think the data migration won't be easy regardless of which method we choose, so I'm indifferent on that point.

However, there are other things to keep in mind should we decide to go with option 2 - 
* Forms/views will need to be rewritten (How would they work by the way?)
* (**All** canopy cover) tests will need to be updated once we change the model
* Someone will need to write *really* good docs to justify/explain why we're storing the canopy cover data this way

**Comment by Kennric** [comment]
Considering the amount of work already done in forms and tests, I am leaning towards keeping that and living with all the rows.

**Comment by leian7** [comment]
The bit method sounds cool. If we do it and end up rewriting the model/views/forms/tests, at least it would maybe be more efficient and less lines of code? Otherwise sticking to what we have now also seems ok.

**Comment by athai** [comment]
@subnomo @alxngyn What are your guys' thoughts on this?

**Comment by alxngyn** [comment]
I'm leaning more towards the side of using existing forms and tests. I think moving to an integer model is a great idea but since the datasheet is already half done (mvc wise) we should just move forward with creating the view. 
We should definitely assess for performance and optimization in the future.

**Comment by athai** [comment]
To be fair, I don't think it'll take much time to rewrite the tests. The current canopy cover views will need to be reworked anyway (yay CSS), so we'll be investing time there in either situation. And if we write good docs, understandability shouldn't be an issue.

My main concern about implementing the bit-shift method has more to do with forms and handling user input. I'm not sure how that will work. 

Overall, switching it up will take time/effort for sure, but I think that if we decide against changing the model now, we won't do it in the future. Canopy cover is a work in progress now, so it's less daunting to scrap and redo. I don't think it's likely that we (or other future devs) will want to rewrite a working data sheet to optimize performance down the line.

Putting the process of rewriting code aside, what form of data would everyone rather work with? For canopy cover, do you think it'd be easier to manipulate 4 integer fields or handle foreign key relationships to another table (24 boolean fields per cardinal direction)?

@Kennric @LyonesGamer @leian7 @alxngyn @subnomo

**Comment by subnomo** [comment]
I do think it's easier to keep it how it is, but I'd also rather not have 24 columns in the db. I missed @LyonesGamer's example, but if we create a custom field that does all the bit-shifting and then exposes 24 boolean fields, then perhaps we won't need to rewrite too much?

**Comment by LyonesGamer** [comment]
@subnomo I had forgotten to restart HAProxy on my webserver after running a bunch of updates. You can see the example again now.

**Comment by subnomo** [comment]
@LyonesGamer Ah, thanks. I see you're doing the bit-shifting in javascript, but I'd prefer to do it on the backend.

**Comment by LyonesGamer** [comment]
@subnomo The benefit of doing it on the frontend is that it gets passed over the network as just a 32-bit integer. Keep it compressed until we need it. Otherwise we're still just converting it from a number to a bunch of boolean fields, we lose most of the benefit of doing it the bit-shift method. On the other hand, doing it in Javascript means we never actually store all those booleans, we just convert the bits to CSS classes on the fly.

**Comment by LyonesGamer** [comment]
I also have an example of how submitting the data will work for data entry. It just prints the integer out to the console.

http://files.lyonesgamer.com/streamwebs-bitshift-canopy-cover-entry.html

**Comment by LyonesGamer** [comment]
Canopy cover models, datasheets, imports, forms, and views are completed.
