### ISSUE TITLE
Create Sites View [8]

### ISSUE THREAD

**Issue by athai** [osuosl/streamwebs#18]
Create the view for the main ``Sites`` page. Include the following:
- [x] A search bar
- [x] A map w/ markers denoting the location's of all sites
- [x] A pull-down menu containing all site names

Note: For the map, keep in mind that we may (later) add functionality that vary marker/pin size depending on the amount of data sheets submitted for the site

Dependent on #15 and #16.

**Comment by LyonesGamer** [comment]
About 3 hours on 5/17
Previously about 12 hours
