### ISSUE TITLE
List of quickfix issues

### ISSUE THREAD

**Issue by athai** [osuosl/streamwebs#187]
The following is a list of minor bugs. They're not high priority nor do they break the functionality of the site - just small inconsistencies to look at if anyone needs something to do.

Feel free to add to the list.

- [x] Make the dragonfly image (for macroinvertebrates) transparent
- [x] Fix the double dropdown menu for schools on the create account page
- [x] Change ``school`` field so that user can choose from a drop-down list on the WQ data sheet and riparian transect data sheet
- [x] Remove site selection from data sheets (site should default to w/e the user is viewing)
- [x] In December, ``test_edge_year_bad_month`` fails
- [x] Why are there two sets of macroinvertebrates images?

Additionally, there are also these issues:
* ~~#186 - Language Menu bugs~~
* #181 - Add link to view all data/Fix double header on WQ graph view

**Comment by leian7** [comment]
Last checkbox satisfied by @subnomo 's #188
