### ISSUE TITLE
Compare site data

### ISSUE THREAD

**Issue by athai** [osuosl/streamwebs#226]
On each site detail page, there should be an option that allows a user to select another site and compare data between the two.

We'll need to visually display graph-able data side-by-side. Further clarification is needed to determine how we should represent the other data sheets.

**Comment by subnomo** [comment]
Any updates on how it should look? I'd like to work on this.

**Comment by LyonesGamer** [comment]
Ideally, the goal would be that while viewing the graph's of one site's data, you can choose to add another site to the page, which would either overlay all of their graphs (that is, one graph with two lines on it, one for each site) or put the sites' graphs side-by-side to compare them.
