### ISSUE TITLE
Add to/Clean up Resources

### ISSUE THREAD

**Issue by athai** [osuosl/streamwebs#246]
TODO:
- [ ] Remove Glossary link
- [ ] Tutorial Videos should lead to a page with videos

We may also want to upload the following data sheets: macroinvertebrates, canopy cover, soil survey, riparian transect, photopoint monitoring (#251)

**Comment by baileysingleton** [comment]
Is there somewhere I can find the videos? I see the ones posted on their current site but I don't know how to get them or find them so I can add them to this site
