### ISSUE TITLE
Text overflow on WQ graphs

### ISSUE THREAD

**Issue by athai** [osuosl/streamwebs#253]
Renee has asked us to look into the overlapping labels on the [water quality graphs](http://streamwebs-staging.osuosl.org/sites/shafer-creek/water/). Iirc, the labels are automatically generated by d3, but we may still be able to rotate their orientation to be more readable.

**Comment by athai** [comment]
@LyonesGamer Would you mind looking into this?

**Comment by LyonesGamer** [comment]
I don't know why we never thought of rotation when we faced this problem last time...

How does this look?

![](http://i.imgur.com/KCQlgFI.png)

@Kennric
