### ISSUE TITLE
Hovering over key should show normal ranges of data

### ISSUE THREAD

**Issue by baileysingleton** [osuosl/streamwebs#303]

**Comment by JerryPeng0112** [comment]
Add hover to data histogram.

**Comment by Kennric** [comment]
@JerryPeng0112 here are documents with information to show in graphs, and a pdf with notes on where things should show up

[Water quality parameters integration.pdf](https://github.com/osuosl/streamwebs/files/1166316/Water.quality.parameters.integration.pdf)
[Parameters sheets_full color.pdf](https://github.com/osuosl/streamwebs/files/1166318/Parameters.sheets_full.color.pdf)
