### ISSUE TITLE
email password reset code to all users

### ISSUE THREAD

**Issue by Kennric** [osuosl/streamwebs#329]
When we deploy to production, we will need to have all imported users reset their password. Django provides a password reset tool which can be programatically activated.

https://stackoverflow.com/questions/30068894/how-to-programmatically-trigger-password-reset-email-in-django-1-7-6

Create a management command that queries all users in the system and sends the reset password email to them. Renee may wish to provide text for an email template for the message, otherwise we can use the default template.

**Comment by Kennric** [comment]
Note: when we import users, we only import those who have logged in within the last three years, so we do not need to filter for activity.

**Comment by hertelc** [comment]
What is the status on this please? I think High Priority items should get an update on a daily basis until we get released. @baileysingleton @JerryPeng0112

**Comment by JerryPeng0112** [comment]
@hertelc Working on this
