### ISSUE TITLE
provide files  for resources

### ISSUE THREAD

**Issue by Kennric** [osuosl/streamwebs#332]
Fixtures for adding resource entries were added, btu the actual files they refer to were not icnluded, resulting in broken thumbnails and links. Add the files/thumbnails to streamwebs_frontend/streamwebs/media/

**Comment by baileysingleton** [comment]
@Kennric Hey Ken, I'm not sure I quite understand. I just made a new branch from develop and all the files are there, except for thumbnails for tutorial videos, which is a little weird, but I couldn't get them to show up at any time. I'll try to fix that thumbnail bug first.

**Comment by baileysingleton** [comment]
@kennric Re did the fixture for tutorial videos, Uploaded thumbnails and fixed the lack of thumbnails. in pr #333
