### ISSUE TITLE
Create Soil

### ISSUE THREAD

**Issue by JerryPeng0112** [osuosl/streamwebs#345]
1. create riparian, should not let user choose school, should choose school associated with user. 
2. Add measurement for distance
3. Add notification after submitting graph

4. Make the circle options multifield

**Comment by baileysingleton** [comment]
From doc:

Can use any school from the drop down list.  Should this be OK?  Should School be auto-selected using school associated with logged in user?

![rip1](https://user-images.githubusercontent.com/26613813/29144704-bb01d148-7d0e-11e7-9d38-3e3202b91568.png)

"Distance from stream" has no note of measurement being entered(feet?, miles?, meters?)
![rip2](https://user-images.githubusercontent.com/26613813/29144712-c1f76efe-7d0e-11e7-844f-798ba7d2f6d7.png)
![rip3](https://user-images.githubusercontent.com/26613813/29144714-c4b81eea-7d0e-11e7-9861-c1ebb3eabeb7.png)



Completion of information addition puts you back to the same screen with no verification that the data was accepted.  There is no notification at the top of the screen like there is on other data entry screens.

**Comment by JerryPeng0112** [comment]
Cannot make the types multifield due to the amount of changes it need, also on the old site it is single field.
