### ISSUE TITLE
Add canopy

### ISSUE THREAD

**Issue by JerryPeng0112** [osuosl/streamwebs#355]
1. Could not create without selecting schools. No notification when not selected

**Comment by baileysingleton** [comment]
"1. When creating a new site and then data set, I could not create the Canopy Cover info without first choosing a school, but the site did not alert me to the fact that a field still needed to be filled out.  It just sat there doing nothing."

![canopy](https://user-images.githubusercontent.com/26613813/29145646-d6b568ba-7d12-11e7-908d-a0758f31da33.png)

**Comment by JerryPeng0112** [comment]
#359 fixed
