### ISSUE TITLE
Account Creation School-Type in instead of DropDown

### ISSUE THREAD

**Issue by baileysingleton** [osuosl/streamwebs#360]
"Could not create an account using any school had to choose one that I knew was part of SMILE program."

So they want to be able to create schools from the register site page? This one is a bit confusing, I think that they should be able to add a school under the school view, because just by typing in a school name doesn't give all the information like the address of school. If we had it this way we would get a cluttered school table. 

![create_school](https://user-images.githubusercontent.com/26613813/29145407-d9b79764-7d11-11e7-8e87-c5786e3814a1.png)

**Comment by leian7** [comment]
@baileysingleton Yeah. Another solution Renee once discussed in the past is just having users request a new school to be added to the list. An admin would then add it.

**Comment by JerryPeng0112** [comment]
Bailey and I discussed about this and we think the best choice would be adding a "add school" page under school tab. This way the user can add school before they sign up.
