### ISSUE TITLE
Typo on Password Reset Page

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#432]
After requesting to reset your password, there is a space missing between "the" and "correct" for step 1. 

"If you don't receive an email:
1. please make sure you've entered **thecorrect** address you registered with.
2. and check your spam folder."

**Comment by hertelc** [comment]
I would also remove the "and" in step 2.

**Comment by emorres25** [comment]
I'd like to take this up.

**Comment by emorres25** [comment]
Can you refer me to the particular file?

**Comment by hertelc** [comment]
Looks like you found it.  👍

**Comment by hertelc** [comment]
Confirmed this is fixed on staging.  Closing issue.
