### ISSUE TITLE
"Add Canopy Cover Data Page" Issues

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#433]
Is the "Weather" field required?  It allows me to save without it.  If required, please make it so.

If you enter an invalid time, when you click submit, all of your canopy selections are cleared.  I didn't notice the first time and submitted data without any canopy cover on accident.  Not an easy way to tell how to fix that...   Is that something an admin has to do?  Could be frustrating to the user.  Perhaps add a message about that on the data screen if the user cannot edit their own submitted data. 

Steps to reproduce the clearing issue:
1. Login to streamwebs
2. I created a new site "Test Site"
3. Click the "ADD DATA TO THIS SITE" drop down and select "Canopy Cover Survey"
4. Enter all fields except for time and click submit.
Result: pop up tells user they require a time to be entered (this is correct/good!)
5. Enter an invalid time (I had entered military time "22:34") and click submit.

Result: All canopy cover selections are cleared and the user is prompted to enter a correct time.

**Comment by hertelc** [comment]
Same response of clearing the canopy information if you forget to enter a date and submit.

**Comment by JerryPeng0112** [comment]
@hertelc I actually discussed with Renee about this, originally i have "optional" text for optional fields, but she suggested not to have them because it "discourages students from entering data"

**Comment by hertelc** [comment]
@JerryPeng0112 , thanks.  I see that now.  The other issue (which I suppose I should have split into 2 tickets) is still present.

**Comment by hertelc** [comment]
Tested with Joseph City Park site and added a Canopy Cover data as listed in the reproduction steps listed in the first post.  This appears to be fixed.  Tested with Win8.1 and Chrome.

**Comment by hertelc** [comment]
Tested on staging today with Chrome and Win 8.1.  Looks good.
