### ISSUE TITLE
Exception thrown when trying to export Water Quality data

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#435]
After entering my water quality data on "Test Site", when I tried to export it, I was given an exception.  See attachment for a PDF of the results shown in my browser.
 
[FieldError at _sites_test-site_water_export_.pdf](https://github.com/osuosl/streamwebs/files/1345186/FieldError.at._sites_test-site_water_export_.pdf)

**Comment by JerryPeng0112** [comment]
This also happens in soil, due to the changed field from data to date and time

**Comment by hertelc** [comment]
What is the status on this please?  I think High Priority items should get an update on a daily basis until we get released.

**Comment by JerryPeng0112** [comment]
@hertelc waiting to be merged

**Comment by JerryPeng0112** [comment]
@hertelc Go to the PR above, it will reference all the issues waiting to be reviewed by @baileysingleton

**Comment by hertelc** [comment]
confirmed fix.
