### ISSUE TITLE
Pressing <Enter> in the Water Quality Data entry causes report to submit

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#436]
For the water quality report, if you are using your keyboard for data entry, you type the temperature, press tab, then mouseover to the "manual" radio button.  I automatically pressed enter to "save" that when I'm assuming it should be a tab to move to the next cell.

I think you should disable <enter> key from doing anything in this form, at least disable from saving/entering the data.

**Comment by baileysingleton** [comment]
@hertelc It seems like it does this on all of them, I'll look into disabling it. Thanks!

**Comment by hertelc** [comment]
Confirmed fix.
