### ISSUE TITLE
Water Quality Sample Results load Backwards

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#437]
When entering Water Quality Data, after you submit the samples are displayed backwards.

So Sample 1 in the data entry, shows as Sample 4 in the resulting report.  Sample 2 shows as Sample 3, Sample 3 shows as Sample 2,   Sample 4 shows as Sample 1.

See attached for a screenshot of data entered and one of the resulting report.  You see the same behavior for both the regular sample data and the Additional parameters data.

**Comment by hertelc** [comment]
What is the status on this please? I think High Priority items should get an update on a daily basis until we get released. @baileysingleton @JerryPeng0112

**Comment by JerryPeng0112** [comment]
@hertelc Waiting to be merged

**Comment by JerryPeng0112** [comment]
@hertelc Go to the PR above, it will reference all the issues waiting to be reviewed by @baileysingleton

**Comment by hertelc** [comment]
confirmed fix.
