### ISSUE TITLE
Macroinvertebrates Minimum Required Fields

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#439]
@rensmere  What are the minimum required fields for the Macroinvertebrates data sheet when adding data?  I'm able to save one with no data in it.  Thanks!

**Comment by rensmere** [comment]
I am not sure that I understand the question.  I don’t know that someone would submit of datasheet if they didn’t have ANY data.  If I am understanding your question then I suppose at a minimum they would find 1 organism.  In terms of the required fields, you can follow the information on the last email.

Renee

**Comment by hertelc** [comment]
Thanks Renee, I think you have answered my question.  I wasn't sure if there were specific other things (like weather, etc) that would be required.   Sounds like the system is working as expected.
