### ISSUE TITLE
MacroInvertebrate totals do not add up

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#440]
I'm not sure if there is a specific formula used, but the total for each type of macroinvertebrate does not match the sum of the numbers in the columns.  See attached screenshots of the data entered and the report generated. 
![macroint_before_1](https://user-images.githubusercontent.com/20323475/31029904-502d6f40-a508-11e7-82e7-322d34d9b363.jpg)
![macroint_after_1](https://user-images.githubusercontent.com/20323475/31029905-50f9917e-a508-11e7-910f-8eab2c946e04.jpg)

**Comment by hertelc** [comment]
These totals are also potentially not in the right columns... see screenshot below. 
![macrointtotals](https://user-images.githubusercontent.com/20323475/31032955-22df962a-a513-11e7-915a-94a5c6f13603.jpg)

**Comment by hertelc** [comment]
I found the document that you can print for this and I see how there is a score for each that you add up.

Perhaps... we might add that score amount in the online survey to help it make better sense to the users who may not know that?

Changing this to enhancement.

**Comment by hertelc** [comment]
@JerryPeng0112  the macroinvertebrate total was working correctly before and now it is incorrect.  See my notes above.  You can also refer to the paper copy of the form for how it adds up.  You don't add up the # of bugs, you add up the scores given to any of the populated fields.

**Comment by JerryPeng0112** [comment]
@hertelc I tried to replicate the bug but I can't, can you provide the link for that specific datasheet?

**Comment by hertelc** [comment]
http://streamwebs-staging.osuosl.org/sites/test-site/macro/361/

**Comment by JerryPeng0112** [comment]
@hertelc I think it is displaying correctly on my site. The data is different from the screensheet above

**Comment by ramereth** [comment]
It seems to be working for me.

**Comment by hertelc** [comment]
Lance, The totals do not add up directly.  Each section is worth a certain amount of points and THOSE get added up.  Jerry and I talked, I’m pretty sure he understands the change needed.


CARRIE HERTEL, PMP, CASS Director – SDG, TL, IoT
Oregon State University | EECS/CASS | 541-737-6012
cass.oregonstate.edu

**Comment by JerryPeng0112** [comment]
@hertelc This is fixed in one of the PRs waiting to be reviewed

**Comment by hertelc** [comment]
Thanks!  I’m not in the project as much as you guys are.  Could someone let me know when it is on staging and I’ll take a look?

CARRIE HERTEL, PMP, CASS Director – SDG, TL, IoT
Oregon State University | EECS/CASS | 541-737-6012
cass.oregonstate.edu
