### ISSUE TITLE
Riparian Transect Report is backwards

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#441]
The Zones are displayed backwards for the Riparian Transect report.  See attached screenshots for data entry and then the subsequent report. 
![rip_before_1](https://user-images.githubusercontent.com/20323475/31030300-b1cbccf0-a509-11e7-9fe3-751ffed2e8a5.jpg)

![rip_after_1](https://user-images.githubusercontent.com/20323475/31030339-d09e59d6-a509-11e7-877f-a544cd7de734.jpg)

**Comment by hertelc** [comment]
What is the status on this please? I think High Priority items should get an update on a daily basis until we get released. @baileysingleton @JerryPeng0112

**Comment by JerryPeng0112** [comment]
@hertelc Waiting to be merged

**Comment by JerryPeng0112** [comment]
@hertelc Go to the PR above, it will reference all the issues waiting to be reviewed by @baileysingleton

**Comment by hertelc** [comment]
confirmed fix
