### ISSUE TITLE
Sorting of Schools in DataSheets Area

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#446]
I have a site "Test Site" with many schools who have contributed datasheets to the site.  How is that list currently ordered?  It does not appear to be in school alphabetical order so I wasn't sure...?

@JerryPeng0112 @baileysingleton

**Comment by JerryPeng0112** [comment]
@hertelc Each school has an id, and it is sorted with that id. Maybe we should try and make it sort alphabetically?

**Comment by hertelc** [comment]
@JerryPeng0112  I think that would be a good idea.  As schools get added that ID won't be in alphabetical order anymore.  It looks like there aren't a ton of schools contributing all of the time.  I think this can be an enhancement.
