### ISSUE TITLE
Riparian & Aquatic Survey navigation is different

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#447]
In the other data sheets I see a button that says "Back to <site>".  In the New Riparian and Aquatic Survey page (and results page) you have to click the blue "<site>" link to return.

This should be updated to match the other pages unless there is a reason not to.

**Comment by baileysingleton** [comment]
Whoops, I'll get on that!

**Comment by hertelc** [comment]
Confirmed fix.
