### ISSUE TITLE
Recommend opening new windows for external links

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#448]
I'm testing in Chrome on Windows 8.1.  In the "Resources" section, I recommend making the links that open files to print or that go to external websites (like NOAA) open in a new tab/window.   Otherwise users are directed away from the site and if they close the tab they have to re-enter the streamwebs site and try to remember where they were.  :)

**Comment by hertelc** [comment]
@rensmere you would know better if this is a requirement and/or something that should be in the first release.

**Comment by baileysingleton** [comment]
@hertelc Think we could combine this issue and #431 and open the add school in a new tab too?

**Comment by hertelc** [comment]
If you open a new tab for the new school will the old tab update with the new school?

CARRIE HERTEL, PMP, CASS Director – SDG, TL, IoT
Oregon State University | EECS/CASS | 541-737-6012
cass.oregonstate.edu

**Comment by hertelc** [comment]
Also, lets please make sure you guys are following the priority order for work via the Kanban board.  This is a lower priority item. :)

**Comment by JerryPeng0112** [comment]
@hertelc @baileysingleton If we make it open a new tab when adding school, the old page will not be updated. We might have to find other solution for that, or just leave it that way.

**Comment by hertelc** [comment]
confirmed external links open new tab.
