### ISSUE TITLE
Typo in About page?

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#451]
@rensmere, this is the text on the About page and I think there is a typo in the bolded text portion below.  Maybe should be "to conduct hands-on" ?

The StreamWebs Student Stewardship Network is an educational platform that provides teachers and students with resources **to conduct based hands-on** watershed stewardship projects.

**Comment by rensmere** [comment]
"To conduct hands-on" is correct. Thanks for catching that!

On Sep 29, 2017, at 3:02 PM, Carrie Hertel <notifications@github.com<mailto:notifications@github.com>> wrote:


@rensmere<https://github.com/rensmere>, this is the text on the About page and I think there is a typo in the bolded text portion below. Maybe should be "to conduct hands-on" ?

The StreamWebs Student Stewardship Network is an educational platform that provides teachers and students with resources to conduct based hands-on watershed stewardship projects.

**Comment by JerryPeng0112** [comment]
@hertelc Fixed in PR, awaiting review
