### ISSUE TITLE
Paper only Datasheet references

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#452]
Issue comes out of #434 

Any of the datasheets in the resources section that does not have a corresponding online version, please add "paper version only" under the name of the data sheet.  In small text or parentheses?  Something that isn't too obtrusive, but obvious that only the paper version is available.

**Comment by JerryPeng0112** [comment]
@hertelc I think Renee would like the "pebble count" and "invasive species" sheets to be removed from the site. For the stream flow we can do add a no online version test for it.

**Comment by hertelc** [comment]
@rensmere  can you confirm if you only want to keep the Stream Flow sheet and remove Pebble Count and Invasive Species?

**Comment by rensmere** [comment]
I want to keep all the sheets.

On Oct 2, 2017, at 6:30 PM, Carrie Hertel <notifications@github.com<mailto:notifications@github.com>> wrote:


@rensmere<https://github.com/rensmere> can you confirm if you only want to keep the Stream Flow sheet and remove Pebble Count and Invasive Species?

**Comment by hertelc** [comment]
Thanks for the confirmation.  @JerryPeng0112  Please add the paper only to any datasheets that do not have an online format.

**Comment by JerryPeng0112** [comment]
@rensmere Just fixed the fixture, we need to delete the resources and reload the fixtures

**Comment by ramereth** [comment]
@JerryPeng0112 should I do that now on staging?

**Comment by JerryPeng0112** [comment]
@ramereth sure,

**Comment by hertelc** [comment]
confirmed fixed
