### ISSUE TITLE
Riparian Aquatic Survey date_time format

### ISSUE THREAD

**Issue by JerryPeng0112** [osuosl/streamwebs#455]
Needs to be changed from "date" to "date" "time" "AM/PM"

**Comment by hertelc** [comment]
@JerryPeng0112  was this a field change?  As in, there was only a date before and now this matches the other data sheets having a date, and a time, and am/pm selection?  I can't see the old implementation to compare.   Thanks!

**Comment by ramereth** [comment]
@hertelc the production site should have the old implementation still

**Comment by hertelc** [comment]
I wasn't able to find a way to add any datasheets on the old site, even after I created an account.  Not sure if I have permissions so I wasn't able to compare.

On Oct 30, 2017 8:38 AM, Lance Albertson <notifications@github.com> wrote:

@hertelc<https://github.com/hertelc> the production site should have the old implementation still

**Comment by ramereth** [comment]
Oh right because they wouldn't be imported. I know the old site only showed the date with no time or AM/PM, this added that so it would replicate the old site.

**Comment by hertelc** [comment]
Ok, sounds good!

**Comment by ramereth** [comment]
@hertelc so is this one confirmed resolved?

**Comment by hertelc** [comment]
@ramereth Yes.
