### ISSUE TITLE
Update csv to use current production data before cutover

### ISSUE THREAD

**Issue by ramereth** [osuosl/streamwebs#461]
The current csv data is not current and needs to be updated so that we don't lose data since the last snapshot we took.

@Kennric can you please let me know how you gathered the data?

**Comment by Kennric** [comment]
Csv data is pulled directly from the drupal views interface,  we really hoped we would be done before any new data was added,  as the process is tedious and the import is not idempotent :-(

**Comment by ramereth** [comment]
@Kennric can you please help with the process or come in to show me? It's important that we retain the new data.

**Comment by ramereth** [comment]
I think I've figured out most of the issues related to this. I manually updated data on the old site to reflect the changes we currently have in the csv files. Looks like most of the issues were trailing spaces in site names, duplicate sites (one usually had no data, so I deleted that site), and simply bad data entry. I'll work on a PR which adds a script to update this more automatically and do a little more testing.
