### ISSUE TITLE
Add function to delete/disable datasheets

### ISSUE THREAD

**Issue by JerryPeng0112** [osuosl/streamwebs#464]

**Comment by JerryPeng0112** [comment]
Only admin permission

**Comment by ramereth** [comment]
This is related to #361.

**Comment by hertelc** [comment]
Datasheets can only be deleted by Admin or Teacher roles.

**Comment by NathanTan** [comment]
Ready for testing on 'feat/delete_datasheets' branch.

**Comment by hertelc** [comment]
@NathanTan we need a prompt confirming the user would like to delete.  Its just too easy the way it is now to mess up and once its gone, its gone.  Thanks!

**Comment by NathanTan** [comment]
Can do!

**Comment by hertelc** [comment]
Permanently is misspelled.  Please fix.

**Comment by hertelc** [comment]
Fixed in Dev.
