### ISSUE TITLE
Add more resources

### ISSUE THREAD

**Issue by JerryPeng0112** [osuosl/streamwebs#466]

**Comment by JerryPeng0112** [comment]
Renee provided in the email

**Comment by JerryPeng0112** [comment]
Add new water_quality datasheet, Add more videos, add more guides (curriculum)

**Comment by baileysingleton** [comment]
If this is the stuff she emailed about, like the macro video, water quality video, and classroom field guide, then these are already in there.

**Comment by ramereth** [comment]
@baileysingleton can you please confirm by looking on the prod site?

**Comment by hertelc** [comment]
@ramereth  I'm not sure what was in the email, but I see the following on the production site: Vernier Tutorial Videos, Water Quality Tutorial Video, Macroinvertebrate Tutorial Video, Field and Classroom Investigation Guide.  There are some others in there under Resources but I think this may be what you were looking for?

**Comment by baileysingleton** [comment]
@ramereth Sorry for the late reply, but I just checked on production and they look to be there. I think this issue can be closed.
