### ISSUE TITLE
Photos added to Camera Points from my phone don't load

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#469]
Not sure what the mobile support is, but I can see people adding pictures they took on their phones.  I wouldn't spend too much time on this, but could be worth looking for a bit on why the photos are not displaying.

See the Test Site, Camera Point D.  There are 3 photos I added from my phone.  2 of them were previous pictures and the last was a photo I took with my phone right then to submit. 

http://streamwebs-staging.osuosl.org/sites/test-site/camera/5/photo/8

**Comment by hertelc** [comment]
I'm using a Verizon Android phone with Google Chrome browser.  Android ver 5.1.  Chrome version 61.0.3163.98.

**Comment by ramereth** [comment]
When you go directly to the image nginx returns a 403 forbidden message. Looking at the file on the filesystem, it seems to have permissions which doesn't allow nginx the ability to view the file.

Showing a snippet of what's show in the directory, you can see the last file has the proper permissions:

``` console
-rw-------. 1 streamwebs-staging streamwebs-staging 2814322 Oct  5 17:53 IMG_20171003_194834790.jpg
-rw-------. 1 streamwebs-staging streamwebs-staging 3557866 Oct  5 17:55 IMG_20171003_202201796.jpg
-rw-------. 1 streamwebs-staging streamwebs-staging 2922544 Oct  5 17:56 1507226158953-1908767669.jpg
-rw-r--r--. 1 streamwebs-staging streamwebs-staging  477665 Oct  5 17:19 Lake.JPG
```

I wonder if the ``umask`` is wrong for the streamwebs-staging user. It's currently set as ``0002`` which creates files as ``600``. We should probably change the user umask to ``0442`` which creates files as ``644`` so it's readable by the web server.

**Comment by hertelc** [comment]
BTW, other than the above, the streamwebs site worked really well on my phone.  :)

**Comment by ramereth** [comment]
Looks like we need to add ``FILE_UPLOAD_PERMISSIONS = 0644`` to the ``settings.py`` file. I confirmed it by changing it manually  and having @hertelc try again. I'll manually fix all the current files on staging and I'll make a PR here updating the ``settings.py.dist`` file.
