### ISSUE TITLE
Large Dropdowns are slow on mobile devices

### ISSUE THREAD

**Issue by ramereth** [osuosl/streamwebs#487]
A note from @rensmere:

> Scrolling took FOREVER!  The group whose school started with W took at least 5 minutes to scroll down to W. When teachers then went to enter their data sheets they had to go through the scrolling again so that they could associate their data with the school.  They were SUPER frustrated by this.  **This was on ipads**.
> It would be helpful to add the alphabet up top so people could get to their letter quickly.  The scrolling function on the ipad needs to be improved no matter. 
>

**Comment by ramereth** [comment]
@JerryPeng0112 any progress?

**Comment by JerryPeng0112** [comment]
@ramereth Working on it

**Comment by hertelc** [comment]
@JerryPeng0112  where are we at on this one?

**Comment by hertelc** [comment]
Large dropdowns have been changed to type-ahead fields with lists to pick from.  Closing out this issue as resolved.
