### ISSUE TITLE
Entering data on iPads requires multiple "clicks"

### ISSUE THREAD

**Issue by ramereth** [osuosl/streamwebs#489]
A note from @rensmere:

> To enter their water quality data they all had to click on the water quality button under “Add data to this site” 3 times (I just tried and experienced it myself).

I confirmed this myself using an iPad. It seems as though it doesn't give proper focus using the drop down.

**Comment by JerryPeng0112** [comment]
I'll look into this issue more tomorrow or wednesday

**Comment by rensmere** [comment]
This may be a safari issue.

Renee

**Comment by hertelc** [comment]
I'm bumping this to low priority and will close if we don't get feedback that this is still an issue. I have been testing on the SMILE iPad and I have click issues with other websites too, not just streamwebs.  So I don't think this is something we can fix.

**Comment by hertelc** [comment]
Fixed on staging.
