### ISSUE TITLE
Aquatic Macros Graph Fixes

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#496]
Copied from an email from Renee regarding Aquatic Macros graph.

"•         Macroinvertebrate graphs do not need decimals.
•         We do not need a “time” option on macroinvertebrate page.
•         Histogram graphs needs clarification.  You need to specify what the axis are, it not clear what we are looking at. "

http://streamwebs-staging.osuosl.org/sites/wenaha-river/macros/

1. Remove the decimals
2. Remove the Time option
3. I don't see a histogram, so I'm assuming this is ok.

**Comment by hertelc** [comment]
I think for item 3 maybe she means the Y axis.  Right now there are numbers, but is it a sum?  Average?

**Comment by hertelc** [comment]
@baileysingleton  Just tested this branch on dev.  I have a few things for you to look at.
1. "Species type breakdown" is in a weird spot.  See screenshot below.
2. I don't see any numbers listed or there when I click or mouseover.
3. The pop up images of the various species doesn't seem to be appearing either when I mouse over or click.

![image](https://user-images.githubusercontent.com/20323475/35059151-1074ed0c-fb6f-11e7-969f-ed09911ad8b6.png)

**Comment by baileysingleton** [comment]
@hertelc I'll check this out. I don't remember any of those issues coming up when I merged it in. I'll get on it

**Comment by baileysingleton** [comment]
Locally I can't reproduce these bugs

**Comment by hertelc** [comment]
Ok, please have Lance put your branch on Dev (or you can ??) to review it.  I was testing with Firefox.

CARRIE HERTEL, PMP, CASS Director – SDG, TL, IoT
Oregon State University | EECS/CASS | 541-737-6012
cass.oregonstate.edu

**Comment by hertelc** [comment]
Looks good in staging.  Closing out.
