### ISSUE TITLE
Riparian Aquatic Survey Data missing

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#498]
Staging site compared to old site shows there is a missing datasheet on the staging site:

Riparian Aquatic Survey Data: 10/05/2010 - 9:35am

http://streamwebs-staging.osuosl.org/sites/grande-ronde-river/#1
http://drupal.streamwebs.org/data/riparian-aquatic-survey/grande-ronde-river/10-05-2010

**Comment by hertelc** [comment]
It appears that perhaps the Riparian Survey is missing on all sites?  I also found it to be missing for Imnaha River.
http://streamwebs-staging.osuosl.org/sites/imnaha-river/#1
http://drupal.streamwebs.org/data/riparian-aquatic-survey/imnaha-river/09-27-2017

**Comment by ramereth** [comment]
Looks like this is another point of data that didn't have a data export script nor a drupal export view for it. I'll look into getting this fixed.

**Comment by ramereth** [comment]
@rensmere looks like we didn't implement field notes for Riparian Aquatic Survey Data. Should that be implemented?

**Comment by rensmere** [comment]
I believe all data sheets included space for field notes on the old website.

On Oct 25, 2017, at 11:53 AM, Lance Albertson <notifications@github.com<mailto:notifications@github.com>> wrote:


@rensmere<https://github.com/rensmere> looks like we didn't implement field notes for Riparian Aquatic Survey Data. Should that be implemented?

**Comment by hertelc** [comment]
I just clicked through all of the sheets on the old site and the only one I saw with no Field notes was the Canopy Cover.  The rest have them included.

Carrie

CARRIE HERTEL, PMP, CASS Director – SDG, TL, IoT
Oregon State University | EECS/CASS | 541-737-6012
cass.oregonstate.edu

**Comment by ramereth** [comment]
OK, I'll create a separate issue to track places where the field notes isn't included in the data models.

**Comment by hertelc** [comment]
This looks good to me in testing on staging.  Tested with Win 8.1 and Chrome.
