### ISSUE TITLE
Water Quality Graph Typo

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#499]
The mouse-over information for the temperature graph has a typo.

The last word in the paragraph is "breath" and it should be "breathe"

http://streamwebs-staging.osuosl.org/sites/grande-ronde-river/water/

**Comment by hertelc** [comment]
@CarvellWakeman what branch is this in?  Do I need to have Lance re-deploy to dev to validate?

**Comment by CarvellWakeman** [comment]
This is in the BugFix_Jan2017. Would need to re-deploy to dev to validate.

**Comment by hertelc** [comment]
Still looks like the breath is there instead of breathe.  Low priority issue, but removing the ready for review status.

**Comment by CarvellWakeman** [comment]
The string is manually typed in two places for some reason. Updated on both now.

**Comment by hertelc** [comment]
Confirmed fixed.  Closing.
