### ISSUE TITLE
Field Notes are missing for several data types

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#500]
Not sure if this is across the board or just for this specific instance.

Tested with Chrome on Win8.1
Comparing between Old site and Staging, the field notes are missing for Water Quality.

http://streamwebs-staging.osuosl.org/sites/camp-creek/water/137/
http://drupal.streamwebs.org/data/water-quality/camp-creek/10-04-2011

**Comment by ramereth** [comment]
I've found a few other notes being missing in the following data types:

Soil Survey Data:
http://drupal.streamwebs.org/data/soil/tenino-court-site/11-09-2011
http://streamwebs-staging.osuosl.org/sites/tenino-court-site/soil/8/

Macroinvertebrate Data:
http://drupal.streamwebs.org/data/macroinvertebrate/brice-creek-west-trailhead/09-13-2010
http://streamwebs-staging.osuosl.org/sites/brice-creek-west-trailhead/macro/7/

**Comment by ramereth** [comment]
@rensmere should field notes have been implemented for soil surveys or was that a decision not to do that?

**Comment by rensmere** [comment]
Yes, fieldnotes should’ve been implemented for the data sheets.
Renee

On Oct 25, 2017, at 10:55 AM, Lance Albertson <notifications@github.com<mailto:notifications@github.com>> wrote:


@rensmere<https://github.com/rensmere> should field notes have been implemented for soil surveys or was that a decision not to do that?

**Comment by ramereth** [comment]
This particular issue is actually closed, the additional issues are now documented in #507.

**Comment by hertelc** [comment]
I confirmed Field notes are populating for Water Quality, Macroinvertebrates, and Riparian Transect.  There are no field notes for Canopy Cover, but there was not in the old site either.

I note the other added issues covering the Soil Survey, and Riparian Aquatic Survey to add field notes fields and import data.  With that noted, I think this issue may be closed.

**Comment by hertelc** [comment]
Same observations as above.  I will check Soil and Rip Aq in the other issue.
