### ISSUE TITLE
Site Project Description Field is not migrated from Old Site

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#501]
Reviewing the old site, I noticed that Project Description was not added into the new site.  When I clicked to edit a site, I found the Description field is there, just not populated...

Example:
Staging - http://streamwebs-staging.osuosl.org/sites/imnaha-river/
Old - http://drupal.streamwebs.org/locations/imnaha-river

Here is one I corrected by clicking "Edit Site" button in the bottom of the screen and copying in the Project Description.  This is what it should look like.
http://streamwebs-staging.osuosl.org/sites/camp-creek/
http://drupal.streamwebs.org/locations/camp-creek

**Comment by ramereth** [comment]
Looks like this wasn't included in the data and will need to be added.

**Comment by hertelc** [comment]
This appears to be fixed in my testing on staging with Chrome and Windows 8.1

**Comment by hertelc** [comment]
This still looks good in staging.  Tested with Chrome and Win 8.1
