### ISSUE TITLE
Joseph Prairie Creek is missing Canopy Cover datasheets

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#502]
http://streamwebs-staging.osuosl.org/sites/joseph-prairie-creek/
http://drupal.streamwebs.org/locations/joseph-prairie-creek

I have seen Canopy Cover datasheets on other sites, but it is not appearing for this one in the datasheets table.  Testing with Chrome on Win8.1

**Comment by ramereth** [comment]
Something else I noticed with this is missing data associated with linking the school to the data. I'm working on fixing this at the same time.

**Comment by hertelc** [comment]
This appears to be fixed on staging from my testing.

**Comment by hertelc** [comment]
Still looks good on staging.

**Comment by hertelc** [comment]
Confirmed this is fixed on production.  Closing issue.
