### ISSUE TITLE
Implement field notes in Soil Survey & Rip Aquatic Survey

### ISSUE THREAD

**Issue by ramereth** [osuosl/streamwebs#507]
As stated in #500, we need to implement the field notes in the Soil Survey model and then import the old data.

Examples can be seen here:
http://drupal.streamwebs.org/data/soil/tenino-court-site/11-09-2011
http://streamwebs-staging.osuosl.org/sites/tenino-court-site/soil/8/

**Comment by ramereth** [comment]
Looks like the change I merged duplicated the soil types for some reason on staging.. Let me look into that.

**Comment by hertelc** [comment]
@ramereth it looks like the lines are all combined on the new site.  Is there a return character missing in the old data or is this an import issue?  Look at the two samples you mention at the top of this thread.

**Comment by ramereth** [comment]
@hertelc the data has the newlines, but the HTML rendered page of it doesn't show up. It's more of a styling issue I think. If you look at the source code of the HTML you'll see the newlines there.

**Comment by hertelc** [comment]
Ok, so the data is ok, just the page is styled that way?

CARRIE HERTEL, PMP, CASS Director – SDG, TL, IoT
Oregon State University | EECS/CASS | 541-737-6012
cass.oregonstate.edu

**Comment by hertelc** [comment]
Field notes are included in both Soil and Riparian Aquatic.  I found old data with field notes and confirmed they displayed.  Tested with Chrome and Win 8.1

**Comment by ramereth** [comment]
@hertelc correct
