### ISSUE TITLE
Rip Aqua Form Fields Are not the same as the paper sheet

### ISSUE THREAD

**Issue by baileysingleton** [osuosl/streamwebs#509]
The entry forms for the rip aqua edit does not have options like the table, and the view is bad as well.

**Comment by hertelc** [comment]
@baileysingleton  I am not able to use the old site to compare what it used to look like but in comparing with the paper sheet for this form, how would a user add more plants or wildlife?  The paper sheet has you flip it over and add more.  If the old site also limits the table, then we should keep it that way.

Also, it looks a little messy showing "none" in the table for empty fields.  See screenshot below. 
![survey](https://user-images.githubusercontent.com/20323475/32155115-924e7390-bcf2-11e7-8d4d-7eaf53fc367d.JPG)

**Comment by ramereth** [comment]
@hertelc the old site limited with the amount of fields (six each) so we're mimicking the old site.

**Comment by hertelc** [comment]
@ramereth  did the old site also display the "none" parts?

**Comment by ramereth** [comment]
@hertelc I don't recall

**Comment by hertelc** [comment]
![image](https://user-images.githubusercontent.com/20323475/32194712-63d49d2e-bd78-11e7-93e4-4143570c8387.png)

It does not have the "none".  This is a screenshot from the old site.

**Comment by ramereth** [comment]
@baileysingleton can you please take a look and see if you can remove the "None"'s?

**Comment by baileysingleton** [comment]
@ramereth I can look into removing the nones

**Comment by ramereth** [comment]
@baileysingleton seems to only happen when you enter data using the form. I.e. when I imported old data, it was fine.

**Comment by baileysingleton** [comment]
@ramereth I noticed that too, I was a little confused at first when I was checking out the imported data. Should be simple to remove the None option, going to get on that

**Comment by hertelc** [comment]
Question out to Renee on if the "none" option should have been removed... there is not a way for the user to leave an option "Blank" because none of that category exist.

**Comment by hertelc** [comment]
@baileysingleton  The option for "blank" in the categories for the Riparian Aquatic Datasheet need to be returned.   This is what we see on the current production site now.  A field should be considered blank unless an option is selected. 
![ripaquablanks](https://user-images.githubusercontent.com/20323475/32758008-2c3eeec6-c897-11e7-95c9-7d57c6b37baf.JPG)

**Comment by baileysingleton** [comment]
Still waiting for review on this PR #543 to put back the blanks

**Comment by hertelc** [comment]
On Staging, this looks fixed! http://streamwebs-staging.osuosl.org/sites/outer-space/rip_aqua/edit/

@baileysingleton I think we can close this one out.

**Comment by hertelc** [comment]
Closing this issue as fixed.
