### ISSUE TITLE
Aqua Macroinvertebrate DataSheet Question

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#512]
@rensmere I have a couple of questions around the Macroinvertebrate datasheet:

The paper version of the datasheet has you circle a value (1, 2 or 3) and then add up those numbers for the sensitivity totals.  The use that number to come up with the Water Quality rating.
   a.  The old site used to add up the total number of counted types and not the weighted values
   b. The new site follows the paper version.  Is this what you would like?

**Comment by hertelc** [comment]
Also, the Macroinvertebrate graph currently looks like it is averaging the samples of each instead of displaying a total that was counted which is different than the old site.  Should this be a total or an average? Thanks!

**Comment by rensmere** [comment]
I think that as long as we are being consistent with the way the data is being displayed that is fine.  I believe that Ken, the former team of students and I discussed this over a year ago and determined that the counts were likely inaccurate and the weighted values probably made more sense.  As long as the user can see the correct breakdown of sensitive, somewhat sensitive and tolerant species are we are good.

Thanks.

Renee

**Comment by hertelc** [comment]
Thanks Renee,  Just to clarify,  the output on the datasheet will match the paper sheet in that it will display the sum of the weighted values.  The histogram will be a display of the average of each species across the graphed time period.

CARRIE HERTEL, PMP, CASS Director – SDG, TL, IoT
Oregon State University | EECS/CASS | 541-737-6012
cass.oregonstate.edu

**Comment by rensmere** [comment]
Yes, the output on the datasheet will match the paper sheet and display the sum of the weighted values.  Is there a histogram for macros?  I think just bar/pie/line (time).  The only ones that I think really matter to us are the bar and pie graphs as those are mimicking old site.
The time was added by student without our consult and we decided to leave it but honestly I think it will be confusing for students.

Thanks!  Renee

**Comment by hertelc** [comment]
I asked them to take out the time, so that is on the list. I suppose I mean bar graph, not histogram. ☺  Sounds like we are on the same page.

CARRIE HERTEL, PMP, CASS Director – SDG, TL, IoT
Oregon State University | EECS/CASS | 541-737-6012
cass.oregonstate.edu

**Comment by rensmere** [comment]
Great!  Thanks.

Renee
