### ISSUE TITLE
Mussell/Clam Icon broken on Macro Graph

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#513]
http://streamwebs-staging.osuosl.org/sites/carries-test-site/macros/

Tested on my own site using stage, but you can use any site with a count for the Mussel/Clam in the Macroinvertebrates graph.

When you mouse over the "Mussel/Clam" section in the graph for the Somewhat Sensitive Species, the icon that displays is broken.

**Comment by ramereth** [comment]
I confirmed this is broken when you run a local instance of it. I suspect the image file is just corrupted somehow.

**Comment by baileysingleton** [comment]
@hertelc On branch BugFixDec2017

**Comment by hertelc** [comment]
@baileysingleton you fixed the graph, however... now the datasheet is broken.  When you go to add data, the field is now at the bottom of the first column.  In viewing an already populated datasheet, the field is back at the top, but in both cases the image is broken.  Reassigning back to you.

**Comment by hertelc** [comment]
@CarvellWakeman The icon looks good, but when I go to enter the clam/mussel data in the datasheet, it shows under the first column "Sensitive".  It should be the top option in the "Somewhat Sensitive" area.  When I save, it goes to the correct place.

**Comment by CarvellWakeman** [comment]
Pushed a fix to BugFix_Jan2017

**Comment by hertelc** [comment]
Looks good!  Closing issue.
