### ISSUE TITLE
Search Sites no long displays locations on map

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#515]
Tested on Staging 10/27/17 around 4:15 pm.  Tested with Win 8.1 with latest Chrome and Firefox.  Also tested on my Android phone with Chrome.

I am not able to see any of the sites listed on the map.  You can still select from the drop down box at the bottom, but something is definitely broken here.

![image](https://user-images.githubusercontent.com/20323475/32128594-dab6d3e0-bb33-11e7-8657-188cd99e5d82.png)

**Comment by hertelc** [comment]
Log file from Chrome Console output. 
[streamwebs-staging.osuosl.org-1509147141701.log](https://github.com/osuosl/streamwebs/files/1423718/streamwebs-staging.osuosl.org-1509147141701.log)

**Comment by ramereth** [comment]
Looks like we load the site descriptions in the java script and sites that have newlines have created broken java script and thus breaks the map. Let me see what we can do to work around it. I'm not sure why we include the description in there anyway.

**Comment by hertelc** [comment]
@ramereth  should this be in the Staging location for the project now?

**Comment by ramereth** [comment]
@hertelc no, I haven't pushed it to staging yet, just pushed it to a dev instance so you can verify it.

**Comment by hertelc** [comment]
This looks good on staging.  Tested with Chrome, Win8.1.
