### ISSUE TITLE
Test site in the Production area:  Outer Space

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#517]
@rensmere  want to make sure this truly is a bogus site that should be taken down before I ask the team to do so.  I found the site "Outer Space" in the old streamwebs site and confirmed it is also on the production, live site.  Can you confirm this is ok to remove to help clean up data?  Is that something an admin could do?  Thanks!

**Comment by rensmere** [comment]
Are the @rensmere questions for me?  I don’t have any context for the emails coming through.  Can I be taken off the GitHub thread?  Thanks!

Renee

**Comment by hertelc** [comment]
Hi Renee,. That question is for you.  I found a site on the Stream webs live site called "Outer Space" that I'm pretty sure is a bogus test site.  I was hoping you could take a look at it and confirm.  Go to streamwebs.org and search for that site.  Thanks!

On Oct 30, 2017 11:13 AM, rensmere <notifications@github.com> wrote:
Are the @rensmere questions for me? I don’t have any context for the emails coming through. Can I be taken off the GitHub thread? Thanks!

Renee

**Comment by rensmere** [comment]
Hi Carrie,

I am not sure how to verify whether this is someone’s site or not?  Since it is a statewide database I don’t have knowledge of individual sites. I will say that it appears to be in the middle of nowhere.  That said, StreamWebs is an educational tool so someone may be using it as a practice site?  Does it appear to be an issue?  Thanks.

Renee

**Comment by hertelc** [comment]
Ok, if you are ok with it there, we will leave it.  Was just trying to help clean up some data.  Thanks, I’ll close this out.

CARRIE HERTEL, PMP, CASS Director – SDG, TL, IoT
Oregon State University | EECS/CASS | 541-737-6012
cass.oregonstate.edu
