### ISSUE TITLE
Implement Server-Side validation

### ISSUE THREAD

**Issue by baileysingleton** [osuosl/streamwebs#530]
After getting a confirmation from Renee, we will need to go in and fully re-vamp the validation technique of the forms for Streamwebs. Following https://github.com/osuosl/streamwebs/pull/521 we should go ahead and implement this new style that will work on all modern browsers.

**Comment by baileysingleton** [comment]
Update: Renee said it looks great. Good to go

**Comment by hertelc** [comment]
@baileysingleton can this be closed in favor of #575?

**Comment by hertelc** [comment]
This has been implemented.
