### ISSUE TITLE
Export of Riparian Aquatic Survey gives Server Error

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#538]
When I tried to export any Riparian Aquatic data I get "Server Error (500)".

http://streamwebs-staging.osuosl.org/sites/wenaha-river/rip_aqua/export/

**Comment by hertelc** [comment]
Used Blocked Flag as this issue blocks pushing staging to production.

**Comment by ramereth** [comment]
This is likely related to #519 somewhat.

**Comment by hertelc** [comment]
This looks good.   I'm able to export Riparian Aquatic data.  Tested in Chrome and IE.
