### ISSUE TITLE
Issues with reset password and then logging in

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#544]
I am able to get the reset password option to work for me.

However... once I click on the link in my email and update my password, if I click the "login" button in the menu instead of the link on the page, then login, I am sent back to the confirmation page:

1. http://streamwebs.org/password_reset/
2. http://streamwebs.org/password_reset/done/
3. Use the link from my email: http://streamwebs.org/reset/MjI1/4r8-f23fc272401e12ca9ae6/
4. http://streamwebs.org/reset/done/

Click "Login" instead of the "sign in" link. 
5. http://streamwebs.org/login/?next=/password_reset/done/
Login with correct credentials

Resulting page: 
6. http://streamwebs.org/password_reset/done/
I am logged in, but this would be very confusion for many users.

**Comment by maccelerated** [comment]
This could be very difficult to stop from happening. Zach suggested preventing the login button from redirecting to the last page at all, and instead of going to home page always.

**Comment by CarvellWakeman** [comment]
Basically: when would the user ever need to be redirected after _clicking_ the login button? In almost all cases, they are directed to the login page when they try to access a login-required page, and then login redirects them back to where they were.

**Comment by hertelc** [comment]
I'm going to close this out for now.  We can re-open if it ends up being a real problem.
