### ISSUE TITLE
Implement https on production site and redirect all traffic to https

### ISSUE THREAD

**Issue by ramereth** [osuosl/streamwebs#546]

**Comment by ramereth** [comment]
Looks like we have some mixed content warnings we need to fix before we can do a real redirect. Re-opening until that gets resolved.

**Comment by hertelc** [comment]
I also looked through this one and did not see any mixed content errors.

**Comment by ramereth** [comment]
Deployed on production. Once we've checked that everything is working properly, I'll work on adding the redirect.

**Comment by hertelc** [comment]
@ramereth I think we can close this issue out?

**Comment by hertelc** [comment]
Closing as redirect is added in Prod.
