### ISSUE TITLE
Manage Accounts button needs removed for Contributors

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#572]
Logged in as a contributor for Ackerman Middle School,  if I "view schools" and click on Ackerman Middle School, I see a "Manage Accounts" button.

When I click on it, I get a "403 Forbidden".  This button should not show for contributors, only Admin/Super Admin

**Comment by hertelc** [comment]
@baileysingleton is this completed?

**Comment by CarvellWakeman** [comment]
@hertelc I believe so, https://github.com/osuosl/streamwebs/commit/da4d3d7de744e734b0ab383481eb5e6beede0fda

**Comment by hertelc** [comment]
confirmed this is fixed.
