### ISSUE TITLE
Users with the Approved variable set to false should not be able to log in

### ISSUE THREAD

**Issue by CarvellWakeman** [osuosl/streamwebs#573]
TEST:
1). Create a user for an existing org
2). Try to log in as that user
Expected: Redirected to login page with error message about user not being approved

1). Navigate to org of previously created user (admin)
2). Approve user as contributor and/or editor
3). Log in as new user
Expected: Login success. If user was approved as editor, they can access the manage accounts page for their org

1). Create a user for a new org
2). try to log in as that user
Expected: Redirected to login page with error message about user not being approved

**Comment by hertelc** [comment]
Whew, I was wondering about this.  Glad I'm not crazy. :)

**Comment by CarvellWakeman** [comment]
@hertelc Ready for review!

**Comment by hertelc** [comment]
Validated this is fixed via http://streamwebs-dev.osuosl.org:8000/
