### ISSUE TITLE
Water Quality Averages need to be added 

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#574]
The Water Quality datasheet had averages for all of the data components in the previous system and it has been requested we bring those back in to the current system.  

Some Details:
1. Only applies to Water Quality datasheet.
2. Only average data entered
         For example, if no PH values are added, you don't display an Average PH.
3. For Water and Air temperature, please make sure the values are displayed in both F and C
4. Include units for all average values displayed.
5.  I'm not sure on location for this data as the old site did not list each of the data points before.  Open for discussion.  My gut feeling is an average below the row of data for each would be appropriate.

Water Temperature     Value    Value   Value   Value
           Average           Temp F     Temp C

Maybe an averages section at the top of the screen once submitted??  We will have this data to display for old submissions as well. 

Below is a screen shot of the data from the old site:

![image](https://user-images.githubusercontent.com/20323475/34020849-5b7974c4-e0eb-11e7-87c9-860baa655ec9.png)

**Comment by NathanTan** [comment]
Note: Both F and C need to be displayed for temperature averages

**Comment by hertelc** [comment]
The water/air temp averages work great if you only use F.  If you use C for your sample temperatures, the top average number displays the C average, but it is the F number.  It then calculates the C average based on the F value (which is actually the average of the C temps).

@CarvellWakeman, FYI in case Nathan is not in the morning.

**Comment by hertelc** [comment]
This looks good.  It even handles when you put in a 0 or leave a field blank.  The averages are done correctly.  Closing issue.
