### ISSUE TITLE
AttributeError at /register/ 'Settings' object has no attribute 'STREAMWEBS_PROTOCOL'

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#580]
Error when registering a new user.  See attached screenshot of the form just before I submitted it.   Also attached is the error log information.

Steps to Reproduce:
1. Click "Create Account"
2. Fill in information
3. Click "Create Account"

[AttributeError at _register_.pdf](https://github.com/osuosl/streamwebs/files/1564322/AttributeError.at._register_.pdf)

![newuserjanedoe](https://user-images.githubusercontent.com/20323475/34064612-2dbbc680-e1af-11e7-8d21-0f6b6a893e80.JPG)

**Comment by hertelc** [comment]
Tested using: http://streamwebs-dev.osuosl.org:8000

**Comment by CarvellWakeman** [comment]
Occurs for same reason as #581

**Comment by hertelc** [comment]
No longer an issue.
