### ISSUE TITLE
Error when Approving Accounts as Editor

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#581]
1. I created 2 accounts for approval.
2. I then logged in as the Editor for Ackerman Middle (user hertelmc1).
3. In "Manage Account" I selected the user hertelmc@gmail.com and denied their account.  That seemed ok.
4. I clicked on the contributor box and Apply for the kolstadc@gmail.com account and received an error.
5. After saving that error page for this bug, clicked the back button on the browser (Chrome).
6. I then clicked on the Editor box and clicked Apply again.  Same error.
7. I then clicked on "Manage Account" to refresh the page and now... I have kolstadc@gmail.com user in BOTH places...  which should not be allowed.

[AttributeError at _schools_9_manage_accounts_.pdf](https://github.com/osuosl/streamwebs/files/1564350/AttributeError.at._schools_9_manage_accounts_.pdf)

![approvecontributor](https://user-images.githubusercontent.com/20323475/34064941-fdcbc936-e1b1-11e7-8363-91564d991140.JPG)

**Comment by hertelc** [comment]
Note, the action seems to be happening even with the error.

**Comment by CarvellWakeman** [comment]
This variable is in the settings.py.dist file. If this didn't make it into the deploy than this error would occur. Perhaps these global settings need to be placed in a different file?

**Comment by hertelc** [comment]
@ramereth see comment above.

**Comment by hertelc** [comment]
Also note: tested using http://streamwebs-dev.osuosl.org:8000

**Comment by CarvellWakeman** [comment]
The error occurs when an email is sent because it uses those variables to know where to send the email and what the URL of streamwebs is.

**Comment by hertelc** [comment]
Verified this issue is fixed.
