### ISSUE TITLE
Macroinvertebrates field notes are misplaced on screen

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#585]
The field notes are in an odd place and have a broken image for the Macroinvertebrates datasheet.

Tested with both Chrome and Firefox.

http://streamwebs-dev.osuosl.org:8000/sites/fall-creek-ohrc/macro/edit/

![image](https://user-images.githubusercontent.com/20323475/34065497-10bcf902-e1b7-11e7-8887-acb65f187a25.png)

**Comment by NathanTan** [comment]
I've looked everywhere for this image file and could not find it. I was also unsuccessful at submitting the form and viewing any kind of macro invertebrate from any permission level. 
If we were to have the image file making it show in the edit page would be trivial, but I searched through commits up to almost a year ago and found to such image.

**Comment by hertelc** [comment]
It appears that the first macro-invertebrate is missing from the page: Caddisfly.  This has then shifted all of them and the last one that says field notes should actually be Mosquito Larva.

**Comment by hertelc** [comment]
Confirmed this is fixed.
