### ISSUE TITLE
Unable to register new user with New Org.

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#596]
Tested on staging.

I had attempted to create a user with an email that was already in the system.  I was given an error that an email address already existed.

Later on, I tried Registering a new school and the screen cleared other than name and email, but I did not see any other messages.  I'm assuming this is also a duplicate email error?  

I don't have privledges atm to check if a duplicate email exists.  I was on staging and trying to use kolstadc@gmail.com.

**Comment by hertelc** [comment]
Well.... maybe it just doesn't give me a submission successful message??  I tried with an email that I know for sure is not in the system yet and saw the same behavior.

**Comment by NathanTan** [comment]
The current problem is that when making a new organization, the organization name does not get filled out in the profile_form (The UserProfileForm), thus the profile_form is invalid and the process halts right there. 
So if the school_form is valid, then the profile_form should probably use the organization information from the school_form.
This happens in the 'def register' function in general.py

**Comment by CarvellWakeman** [comment]
If you register a new school but don't do everything correctly, the page will come back with errors but the new org section will not expand. Opening it will reveal the errors that need fixing. Perhaps this is related.

**Comment by hertelc** [comment]
I just tried this again and re-expanded the "New" org page and I didn't see any errors there.

**Comment by CarvellWakeman** [comment]
Found out it's because when a new school is made, the school field is not filled out. This results in the form being invalid. There is no error because the autocomplete field is custom and the validation doesn't know where to put the errors. When the register page server validation is done, the errors will display correctly.

Working on fixing.

**Comment by hertelc** [comment]
Confirmed this looks good.  Will do deeper testing on 1/2, but was able to have a new org and user join as expected on the Dev site.
