### ISSUE TITLE
Create Account Page, School Selection Validation Error Missing

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#601]
Tested with the SMILE iPad.  If you fill out all of the fields EXCEPT the School and click "Create Account", the submission will fail, but no message appears to tell the user why.

**Comment by CarvellWakeman** [comment]
This is fixed in the feat/server_validation branch, which is merged into develop

**Comment by hertelc** [comment]
I will test this once in staging.

**Comment by hertelc** [comment]
fixed in staging.  Closing issue.
