### ISSUE TITLE
Need date picker or validation for statistics page

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#602]
http://streamwebs-staging.osuosl.org/statistics/

There is a start and ending date for displaying information on the status, but there isn't any validation on the dates entered.  Need to either add a date picker or put in the "hint" on the formatting required (mm/dd/yy) and some validation.

**Comment by baileysingleton** [comment]
Fix has been added into PR #606

**Comment by hertelc** [comment]
Looks good!  Closing issue.
