### ISSUE TITLE
Staging site - login page field access

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#603]
On the staging site, when a user is trying to login, they have to click after the gray text to activate the field and type in their username or password.  This is pretty confusing... 

User should be able to click anywhere on the line for username or password to activate the text field for input.

**Comment by CarvellWakeman** [comment]
This has re-occurred in a few places. Normally it was an issue with the container label not having the input-field class, but it's still occurring in login despite that.

**Comment by CarvellWakeman** [comment]
The issue in this case was that the materialize "row" div came _before_ the form tag, and the columns were not the direct parents of the input-field divs.

**Comment by hertelc** [comment]
Confirmed fixed on streamwebs dev.
