### ISSUE TITLE
Make all current users of Streamwebs.org Editors for their schools

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#605]
This needs to be in place before we migrate the Staging site to Prod on 1/2.  Otherwise, users will not have access to do anything until they are approved by an admin.

Make all users Editors for their school.

**Comment by hertelc** [comment]
Not sure I can validate this until its on staging?

**Comment by hertelc** [comment]
@CarvellWakeman staging is not showing this (yet).

**Comment by CarvellWakeman** [comment]
@hertelc Should have been fixed in the last dev release, we will test when dev goes to staging by deploying without migrations, checking that most users are contributor (org_author), applying migrations, and checking that all users are editor (org_admin).

**Comment by hertelc** [comment]
Works!
