### ISSUE TITLE
Update new-org-request to send emails to all super admins instead of testing@streamwebs.org

### ISSUE THREAD

**Issue by CarvellWakeman** [osuosl/streamwebs#610]
The code for this is already in place, commented out in the register method of general.py

Switch out the super_admins variable for the current list of recipients ['testing@streamwebs.org'].

Do this before prod, bug after our dev testing

**Comment by CarvellWakeman** [comment]
Also closes #593

**Comment by CarvellWakeman** [comment]
Accidentally closed, still needs review

**Comment by hertelc** [comment]
This is now going to: requests@streamwebs.org

**Comment by hertelc** [comment]
Fixed and working in Prod.
