### ISSUE TITLE
iPad and Android: Not able to add a new org

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#611]
When you fill out all of the fields to add a new organization and click "Create Account" you get an error for the school and shows "Selected School: None".

Not able to create a new org/user.

Tested on both iPad and Android.

**Comment by CarvellWakeman** [comment]
Fixed in the BugFix_Jan2017 branch. This was already fixed in the BugFix_Dec2017 branch, but my changes got excluded in a merge.

**Comment by hertelc** [comment]
Looks like the fix is good.

**Comment by hertelc** [comment]
Tyler also confirmed the issue looks fixed.  Closing out.
