### ISSUE TITLE
Mac Safari & Chromebook: Unable to save changes to an account without changing user's email

### ISSUE THREAD

**Issue by gilbertt** [osuosl/streamwebs#612]
When editing an existing user, changes to the user cannot be saved if the user's email has not been changed. Clicking the save button results in an error message: "Email: A user with that email address already exists"

**Comment by hertelc** [comment]
Also seen on iPad

**Comment by gilbertt** [comment]
Same bug applies to contributor accounts. Changes can be saved if the email is removed entirely, then the email can be re-added once it's removed.

**Comment by CarvellWakeman** [comment]
Got a fix for it now, on BugFix_Jan2017. I was using form validation to enforce the email field being unique. It's going to require a big migration and will be a pain later because for some reason emails were never unique before this point.

**Comment by hertelc** [comment]
Fix looks good to me.

**Comment by hertelc** [comment]
Tyler also confirmed.  Closing issue.
