### ISSUE TITLE
Clicking the buttons in the add data drop down on a site is nearly impossible in iPad

### ISSUE THREAD

**Issue by CarvellWakeman** [osuosl/streamwebs#616]
The drop down menu closes whenever an item is clicked. If you hit one of them just right you can get into the menu, but it is very hard.

**Comment by CarvellWakeman** [comment]
Fixed in bugfix branch, needs review on staging when deployed

**Comment by CarvellWakeman** [comment]
There is still an issue where you have to wait a brief moment before clicking any of the buttons in the drop down. If you are too fast then nothing will happen.

**Comment by hertelc** [comment]
Same issue as #489

**Comment by CarvellWakeman** [comment]
I have replaced the materialize dropdowns with buttons and accompanying collection lists which are expanded/contracted with jQuery. It looks almost exactly the same and functions perfectly on the dev site on an iPad and iPhone using Safari.

Fix is on the bugfix/ipad_dropdowns branch.

**Comment by hertelc** [comment]
looks good on staging.   Closing out.
