### ISSUE TITLE
Registration page should enforce a minimum password requirement, just like the password reset page

### ISSUE THREAD

**Issue by CarvellWakeman** [osuosl/streamwebs#617]

**Comment by hertelc** [comment]
What is the minimum password?  Tracy was telling me earlier that it was a little prohibitive at one point for an easy website.

**Comment by hertelc** [comment]
Agreed.

**Comment by CarvellWakeman** [comment]
This is complete in the bugfix/password_strong branch.

This validation will need to be included when #607 is done.

**Comment by hertelc** [comment]
This looks good on staging.  Closing issue.
