### ISSUE TITLE
Page for New Org Approval

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#621]
Is there a way for the super admin to see what orgs need approval without using the email/link?   Not sure the pending schools will be included in the View Schools page or not.

**Comment by CarvellWakeman** [comment]
Pending schools are not included in the schools page. There is also no existing way to view org requests. But it should be fairly easy to do if you put up an issue for it.

**Comment by hertelc** [comment]
Actually, I did see a school in the list that was pending...  I didn't know it was until I did some more digging.  I don't think that's an issue though.  An approve org page would be good.  I'll log it.  Thanks!

On Jan 6, 2018 1:29 PM, Zach Lerew <notifications@github.com> wrote:

Pending schools are not included in the schools page. There is also no existing way to view org requests. But it should be fairly easy to do if you put up an issue for it.

**Comment by hertelc** [comment]
I'm just going to change this to a feature request from a question.

**Comment by CarvellWakeman** [comment]
@hertelc Mark and I discussed this page and how it can tie into the user story for editor replacement.

Ex: An editor leaves an organization or is removed from one, and were the only editor in their organization. A new editor comes in to replace them but has no way to access the account. Currently, the new editor can register for an account and the old editor can approve them. In the scenario where the old editor cannot or will not do that, the super admin will need to step in. This new org approval page can be modified to make this problem easier to solve for super admins.

This "unapproved accounts" page has a first section for new organization requests and provide links to the new org request page.

The second section is for unapproved users, and would display all users in the system who are currently unapproved. It would include links to the user's school's manage accounts page, as well as quick links to deny the user.


If this sounds like a good idea, we can get a mockup made and go from there!

**Comment by hertelc** [comment]
YES!  We weren't sure how the organizations who don't have anyone responding to approve accounts was going to be handled.  This answers that too, so lets do it!

**Comment by CarvellWakeman** [comment]
Done in feat/approval_page branch. PR #628

**Comment by hertelc** [comment]
@CarvellWakeman this looks good.  I'm going to leave the issue open until we test it on staging.  I think you can merge into the develop branch now??

**Comment by CarvellWakeman** [comment]
Merged into develop. Closing this issue.
