### ISSUE TITLE
Water Temperature not graphed for Water Quality

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#622]
https://streamwebs.org/sites/wenaha-river/water/

I'm not seeing any water temperature graphed.  See link.

**Comment by hertelc** [comment]
FYI, I saw it graphed just fine for this site (the one they did at the workshop): https://streamwebs.org/sites/crescent-lake-creek/ 

So maybe an issue with old data graphing correctly?

**Comment by hertelc** [comment]
I'm not seeing any graphs at all anymore in staging... https://streamwebs-staging.osuosl.org/sites/wenaha-river/water/

**Comment by hertelc** [comment]
Assigning to Bailey.  Feel free to share with Jerry.

**Comment by JerryPeng0112** [comment]
#495 
@hertelc 
This is the same issue, I just share some information on that issue. Please take a look.

**Comment by hertelc** [comment]
Reopening so I can validate the fix on staging with all of the merges in before we go to Prod.

**Comment by JerryPeng0112** [comment]
@hertelc 
Oops my bad.
