### ISSUE TITLE
View statistics page should include stats from the current day too

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#624]
A bunch of activity happened today (1/6/18), but when I go to view statistics I can't see any of today's activity.  If I try to pick a date in the future (to try and include today) it won't let me pick a future date.

**Comment by hertelc** [comment]
@baileysingleton I am getting an error when I try to view the stats page:  http://streamwebs-dev.osuosl.org:8000/statistics/.

[UnboundLocalError at _statistics_.pdf](https://github.com/osuosl/streamwebs/files/1674824/UnboundLocalError.at._statistics_.pdf)

**Comment by baileysingleton** [comment]
I'll check it out

**Comment by hertelc** [comment]
Fixed in staging.  Closing out issue.
