### ISSUE TITLE
Water Quality Graphs

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#643]
This is in production, so view the graphs there first.

https://streamwebs.org/sites/cunningham-creek/water/

Question from Cait: "We were able to get two teachers installed as Editors, and the participants entered in data from the Water Quality worksheets using either the Editor or Contributor (workshop22) accounts. Although we can see all the data when we open each entry separately, the only option for GRAPHING is “temperature”. Why can’t we graph any of the other parameters we measured?"

I see that for temperature that there are 2 data points for each datasheet where the others only have 1 and an n/a for the others.  I know we don't graph outliers, but this seems odd.  Can you take a look at the graphing logic and see why only temperature is graphing?

**Comment by baileysingleton** [comment]
Hmm, I thought Nathan and I fixed this issue a while back. I'll look into it. We had issues with data only being graphed with 2 points but I thought we fixed that up.

**Comment by hertelc** [comment]
#622 is blocking my testing of this issue.  I can't see water quality graphs at all right now.

![image](https://user-images.githubusercontent.com/20323475/36503774-1821c958-1703-11e8-9a81-c297a1829f1b.png)

**Comment by JerryPeng0112** [comment]
@hertelc 
Again, this is the same issues on #495. I commented on that one, might need inputs from you to decide what to do next.

**Comment by hertelc** [comment]
Ok, I think I need to have Tracy and Cait think more about those outliers.  @JerryPeng0112 can you provide the logic used for that filter?

**Comment by hertelc** [comment]
@JerryPeng0112 I am not seeing water quality graphed like I would expect using your branch.

Check it out:
https://streamwebs.org/sites/wenaha-river/water/
http://streamwebs-dev.osuosl.org:8000/sites/wenaha-river/water/

**Comment by JerryPeng0112** [comment]
@hertelc 
Yes, the new one is the fixed graph. 
This link: [https://streamwebs.org/sites/wenaha-river/water/](https://streamwebs.org/sites/wenaha-river/water/) is not doing the right thing. The data has both water/air temp. So they should be graphed. Also turbidity 0 is all filtered out by default. We can adjust the filtering functions to accept turbidity 0 on the graph.

**Comment by hertelc** [comment]
@JerryPeng0112 I just looked at this on Dev and it looks good.  Please merge in.

**Comment by hertelc** [comment]
Sorry Jerry, I'm reopening this so I can use this task to make sure I check it on Staging once everything is merged.

**Comment by hertelc** [comment]
@JerryPeng0112  closed again? :)

**Comment by hertelc** [comment]
Looks good in staging.  Closing.
