### ISSUE TITLE
Server Error (500) when creating an account

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#644]
Tested in Firefox and Win 8.1
When creating a new account, the user is directed to this page:
https://streamwebs-staging.osuosl.org/register/
But is given a Server Error (500).  It appears that the account is created correctly however.

Steps to reproduce:
1. https://streamwebs-staging.osuosl.org/
2. Click "Create Account"
3. Fill out First Name, Last Name, valid email, valid password, select Oregon State University for school, click the recaptcha and  "Create Account"
4. User gets Server Error (500)

**Comment by hertelc** [comment]
@ramereth FYI in case this is due to the database changes/update and you know what is going on?

**Comment by hertelc** [comment]
I see the same after I login as admin and approve the account.  https://streamwebs-staging.osuosl.org/schools/942/manage_accounts/

**Comment by baileysingleton** [comment]
@hertelc I can't reproduce the create account bug, it directs me to the correct page. Working on viewing the second one, I need to get an admin account before I can.

**Comment by hertelc** [comment]
I am no longer seeing this issue on staging.   Closing issue.
