### ISSUE TITLE
Edge add data sheet dropdown unresponsive

### ISSUE THREAD

**Issue by anderrob** [osuosl/streamwebs#645]
**Description:**
Clicking "Add Data Sheet" on edge on Windows is unresponsive. Dropdown menu does not appear.

**Steps to reproduce:**
1. Log in
2. Click Search sites
3. On the map, click any of the sites available and click the link to their site
4. Scroll down to the bottom and click "Add Data Sheet"

**Expected Results:**
A dropdown menu appears showing the available data sheet types to add.

**Actual results:**
The wave animation on the button works, but the dropdown never appears.

**Notes:**
This was found on Windows 10 Edge, versions:
Edge 40.15063.674.0
EdgeHTML 15.15063

**Comment by baileysingleton** [comment]
The issue has been found, and a solution is in the works

**Comment by hertelc** [comment]
@baileysingleton tested on Dev and it looks good.  Please merge in.

**Comment by baileysingleton** [comment]
Merged

**Comment by hertelc** [comment]
@baileysingleton reopening so that I can do my final validation on Staging before we go to Prod.

**Comment by hertelc** [comment]
Looks good on staging.  Closing
