### ISSUE TITLE
Remove some of the Resource Items

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#649]
Tracy and Cait would like the these two items to be removed from the Resources page:

* "Upload a New Resource"
* "Educator Kits"

**Comment by baileysingleton** [comment]
@hertelc Do they not want the ability to upload resources? I think they still can do it through the django admin, but this seems more user-friendly

**Comment by ramereth** [comment]
Ya, we don't managed resource removal from the code. It's only there for the initial deployment. We can remove it from the code but if you want it done on the site they need to do it via the admin interface.

**Comment by baileysingleton** [comment]
Gotcha

**Comment by hertelc** [comment]
@baileysingleton Looks good, please merge in.

**Comment by hertelc** [comment]
Looks good on staging.  Ready for Prod
