### ISSUE TITLE
Add sentry.io to Stage and Prod

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#652]
Lance:
I'll make sure you and any of the other devs have access to the sentry.io interface. It has an internal issue tracker for each error so you can track it there and reference them back to github

**Comment by ramereth** [comment]
I need to do the following:

- [ ] Add sentry.io packages to pip and add it to the settings.py.dist file
- [ ] Update ansible deployment to properly setup the the sentry.io client DSNs
- [ ] Deploy on staging and test that it works
- [ ] Cherry-pick the changes made to make this work into master
- [ ] Deploy on production and test that it works
- [ ] Add users to sentry.io so they can monitor the issues as they come up
