### ISSUE TITLE
Weird datasheets

### ISSUE THREAD

**Issue by hertelc** [osuosl/streamwebs#659]
I have found a few odd datasheets with technically no data in them.  Can you do some double checking to make sure this wasn't an import issue somewhere?

http://streamwebs-dev.osuosl.org:8000/sites/bull-run-creek/water/934/

**Comment by hertelc** [comment]
I see the same in production too.

**Comment by JerryPeng0112** [comment]
@hertelc 
The current design does not prevent students from entering a data sheet with no data. Should we change that?

**Comment by hertelc** [comment]
@JerryPeng0112 no, lets not change that, its out of scope.  Now that they have the ability to delete sheets, teachers can clean those up themselves.  If the datasheet is just bad in general, then so be it.  I just wanted to do a double check.

**Comment by hertelc** [comment]
And, I just checked the old drupal site and that datasheet was empty there too.  I'm going to close this issue.
