### ISSUE TITLE
Macroinvertebrate Validators

### ISSUE THREAD

**Issue by athai** [osuosl/streamwebs#78]
http://streamwebs-dev.osuosl.org/sites/streamwebs/files/files/Macros_OSU.pdf

Score is tallied differently depending on the macroinvertebrates' sensitivity to pollution. So validator functions need to be written for the following:
* Sensitive Total
* Somewhat Sensitive Total
* Tolerant Total
* Water Quality Rating (Which totals the above scores)

Refer to the datasheet linked above for more detail.

**Comment by cthalmann** [comment]
closed via #84
