### ISSUE TITLE
Cardinal Box Validator for the Canopy Cover Survey

### ISSUE THREAD

**Issue by athai** [osuosl/streamwebs#79]
The number of shaded square per cardinal box cannot exceed 24.

Note: May have to hold off on this issue until the CC model is merged.

http://streamwebs-dev.osuosl.org/sites/streamwebs/files/files/Canopy_OSU.pdf

**Comment by cthalmann** [comment]
Going to hold off on doing this until the CC model is merged.

**Comment by cthalmann** [comment]
Closed via #105

**Comment by cthalmann** [comment]
Closed via #105
