### ISSUE TITLE
Data sheets

### ISSUE THREAD

**Issue by rensmere** [osuosl/streamwebs#8]
Edit data sheets back into rows of 3-4 with name of sheet underneath or next to.

**Comment by Kennric** [comment]
Some of the data sheets' thumbnail images are links to images at http://www.thefreshwatertrust.org/ - but it appears that many of those no longer exist or have moved. I think the entire data sheets page probably needs to be re-constructed with data sheets and images on the streamwebs site.

**Comment by rensmere** [comment]
Ok.  I can access all of the data sheets by clicking on the images, is this not the case for you?  Or maybe it is just behind the scenes?

Renee

On Nov 23, 2015, at 11:42 AM, Kennric <notifications@github.com<mailto:notifications@github.com>> wrote:


Some of the data sheets' thumbnail images are links to images at http://www.thefreshwatertrust.org/ - but it appears that many of those no longer exist or have moved. I think the entire data sheets page probably needs to be re-constructed with data sheets and images on the streamwebs site.

**Comment by rensmere** [comment]
Hi Ken,

Can you look into the data graphing error that reads “data column for axis #0 cannot be of type string for the following site on the collection date 9/21/15? http://streamwebs.org/water-quality-data-graphing?site=4976 I will put it into GitHub too.

I have to visit a class next week to follow up with them on this data and would love to have it work.  I tried just doing individual parameters (DO, pH, temp, etc) and unchecked all of them with still no luck.

Thanks!

Renee

**Comment by Kennric** [comment]
I have updated the datasheets page, please check and make sure it looks correct. 

**Important** - don't edit the datasheets page, the Drupal editor strips out tags when it loads the page for editing, meaning it is impossible to edit without Drupal re-formatting everything into a mess. I had to edit in an external editor and paste into the page source, even using the preview button will strip out the formatting.

**Comment by rensmere** [comment]
It looks good Ken!  The only problem is that the water quality sheet is not the updated one (which is the sheet I was trying to add when I messed it up).  The correct water quality sheet includes salinity.

Renee
________________________________
