### ISSUE TITLE
URLs: Standardize routing

### ISSUE THREAD

**Issue by leian7** [osuosl/streamwebs#96]
We need to discuss url routing, specifically what the routing should be for individual data sheet data views. @LyonesGamer is using site slugs and @alxngyn is using site id; i.e.:

localhost:8000/streamwebs/site/**site_slug**/transect/1
vs.
localhost:8000/streamwebs/site/**1**/transect/1.

**Comment by Kennric** [comment]
I'm fine with either - I don't think there is much of a use case for pretty urls for these, it is not something people will need to manually enter, so ids are probably the easiest

**Comment by alxngyn** [comment]
So are we going with IDs instead of slugs?
